services:
  - type: static
    name: true-north-property-group
    buildCommand: npm ci && npm run build
    publishPath: dist
    spa: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
